/*
 * ServerAdvertise.java
 *
 * Created on February 13, 2005, 4:02 PM
 */

package lircom;

/**
 *
 * @author  carlsonj
 */
public class ServerAdvertise extends javax.swing.JFrame {
    
    /** Creates new form ServerAdvertise */
    public ServerAdvertise() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        advertisementPort = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        url = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nickname = new javax.swing.JTextField();
        advertiseButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Service Advertisement Port");
        getContentPane().add(jLabel3, new java.awt.GridBagConstraints());

        advertisementPort.setColumns(40);
        advertisementPort.setText("5891");
        advertisementPort.setMinimumSize(new java.awt.Dimension(200, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        getContentPane().add(advertisementPort, gridBagConstraints);

        jLabel1.setText("Advertisement Service URL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        getContentPane().add(jLabel1, gridBagConstraints);

        url.setColumns(40);
        url.setText("http://schizophrenics.net/yottzumm/lircom/advertise.pl");
        url.setMinimumSize(new java.awt.Dimension(200, 19));
        url.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        getContentPane().add(url, gridBagConstraints);

        jLabel5.setText("Your Server Name");
        getContentPane().add(jLabel5, new java.awt.GridBagConstraints());

        nickname.setColumns(40);
        nickname.setMinimumSize(new java.awt.Dimension(200, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        getContentPane().add(nickname, gridBagConstraints);

        advertiseButton.setText("Advertise");
        advertiseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advertiseButtonActionPerformed(evt);
            }
        });

        getContentPane().add(advertiseButton, new java.awt.GridBagConstraints());

        pack();
    }//GEN-END:initComponents

    private void advertiseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advertiseButtonActionPerformed
                java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    try {
                       Peer p = new Peer();
                       String adurl = "";
			p.setPort(Integer.parseInt(advertisementPort.getText()));
			if (!p.isAlive()) {
			    p.start();
			}
                       adurl = url.getText()+"?port="+advertisementPort.getText()+"&nick="+nickname.getText();
                       System.err.println("url is "+adurl);
                       java.net.URL u = new java.net.URL(adurl);
                       java.net.URLConnection conn = u.openConnection();
                       conn.setDoInput(true);
                       conn.setDoOutput(true);
                       conn.connect();
                       // conn.getOutputStream().close();
                       java.io.BufferedReader br = new java.io.BufferedReader(new java.io.InputStreamReader(conn.getInputStream()));
                       String line;
                       while ((line = br.readLine()) != null) {
                                System.err.println(line);
                       }
                       setVisible(false);
                    } catch (Exception e) {
                       System.err.println("Networking problems "+e.getMessage());
                       e.printStackTrace();
                    }
               }
            });

    }//GEN-LAST:event_advertiseButtonActionPerformed

    private void urlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerAdvertise().setVisible(true);
            }
        });
    }
    public void setChat(Chat chat) {
       this.chat = chat;
    }
    Chat chat;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton advertiseButton;
    private javax.swing.JTextField advertisementPort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nickname;
    private javax.swing.JTextField url;
    // End of variables declaration//GEN-END:variables
    
}
