/*
 * ClientConnect.java
 *
 * Created on February 13, 2005, 3:11 PM
 */

package lircom;

/**
 *
 * @author  carlsonj
 */
public class ClientConnect extends javax.swing.JFrame {
    
    /** Creates new form ClientConnect */
    public ClientConnect(MainWindow mainwin) {
        this.mainwin = mainwin;
	setTitle("Form a connection");
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        connectButton = new javax.swing.JButton();
        harvestButton = new javax.swing.JButton();
        url = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        remoteSites = new javax.swing.JTable();

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });
        jPanel1.add(connectButton);

        harvestButton.setText("Harvest");
        harvestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harvestButtonActionPerformed(evt);
            }
        });
        jPanel1.add(harvestButton);

        url.setText("http://coderextreme.net/advertise.php");
        url.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlActionPerformed(evt);
            }
        });
        jPanel1.add(url);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        remoteSites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nickname", "Remote Server", "Remote Port", "Registration Date", "Connect?", "Connected?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        remoteSites.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(remoteSites);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
     int NICK_COL = 0;
     int HOST_COL = 1;
     int PORT_COL = 2;
     int DATE_COL = 3;
     int CONNECT_COL = 4;
     int CONNECTED_COL = 5;
     private void harvestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harvestButtonActionPerformed
         try {
               String adurl = url.getText();
               java.net.URL u = new java.net.URL(adurl);
               java.net.URLConnection conn = u.openConnection();
               conn.setDoInput(true);
               conn.connect();
               java.io.BufferedReader br =
                       new java.io.BufferedReader(
                       new java.io.InputStreamReader(
                       conn.getInputStream()));
               String line;
               while ((line = br.readLine()) != null) {
                   System.err.println("Read "+line);
                   java.util.StringTokenizer st = new java.util.StringTokenizer(line, "|");
                   String host = st.nextToken();
                   String port = st.nextToken();
                   String nick = st.nextToken();
                   String date = st.nextToken();
                   new PossibleConnection(host, port, nick, date);
               }
         } catch (Exception e) {
             System.err.println("Problems harvesting servers.");
         }
        java.util.Iterator i = PossibleConnection.iterator();
        int row = 0;
        javax.swing.table.DefaultTableModel tm = (javax.swing.table.DefaultTableModel)remoteSites.getModel();
        while (tm.getRowCount() > 0) {
                tm.removeRow(0);
        }
        while (i.hasNext()) {
                System.err.println("got here");
                PossibleConnection pcon = (PossibleConnection)
                    PossibleConnection.get(i.next().toString());
                try {
                    Integer.parseInt(pcon.port);
                    Object rowobj [] = new Object [] {
                            pcon.nick,
                            pcon.host,
                            pcon.port,
                            pcon.date,
                            !pcon.connected,
                            pcon.connected
                    };
                    tm.addRow(rowobj);
                } catch (Exception e) {
                    System.err.println("Bad port "+pcon.port+" on row "+(row+1));
                }
                row++;
        }
	/*
        Object rowobj2 [] = new Object [] {
                            "Guest",
                            "localhost",
                            new Integer(8180),
                            "",
                            new Boolean(false),
                            new Boolean(false)
       };
       tm.addRow(rowobj2);
       */
     }//GEN-LAST:event_harvestButtonActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
   
        javax.swing.table.TableModel tm = remoteSites.getModel();
	boolean found = false;
        for (int row = 0; row < tm.getRowCount(); row++) {
            //System.err.println(row);
            Object obj = tm.getValueAt(row, CONNECT_COL);
            String host = (String)tm.getValueAt(row, HOST_COL);
            String port = tm.getValueAt(row, PORT_COL).toString();
            String nick = (String)tm.getValueAt(row, NICK_COL);
            PossibleConnection pcon = (PossibleConnection)PossibleConnection.get(host, port, nick);
            if (obj != null && ((Boolean)obj).booleanValue()) {
                    try {
                        if (!pcon.connected) {
                            mainwin.connect(host, Integer.parseInt(port));
                            pcon.connected = true;  
		            found = true;
                        }
                    } catch (Exception e) {
                            pcon.connected = false;
                    }
                    tm.setValueAt(pcon.connected, row, CONNECTED_COL);
                    tm.setValueAt(false, row, CONNECT_COL);
            }
        }
	if (found) {
		setVisible(false);
	}
    }//GEN-LAST:event_connectButtonActionPerformed

    private void urlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientConnect(null).setVisible(true);
            }
        });
    }
    public void harvest() {
        harvestButtonActionPerformed(null);
	connectButton.invalidate();
	connectButton.validate();
	harvestButton.invalidate();
	harvestButton.validate();
    }
    private MainWindow mainwin;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connectButton;
    private javax.swing.JButton harvestButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable remoteSites;
    private javax.swing.JTextField url;
    // End of variables declaration//GEN-END:variables
    
}
