/*
 * Alfav02.java
 *
 * Created on February 12, 2005, 11:59 PM
 */

package lircom {
import javax.swing.UIManager;

/**
 *
 * @author  hivechild
 */
public class MainWindow extends javax.swing.JFrame implements java.awt.event.WindowListener {
    
    /** Creates new form Alfav02 */
    public function MainWindow(title:String) throws Exception {
        super(title);
        initComponents();
        // Main_Menu.getPopupMenu().setLightWeightPopupEnabled(false);
        scrollingText.getViewport().setOpaque(false);
	//Orbit2 canvas = new Orbit2();
        //jLayeredPane2.add(canvas, javax.swing.JLayeredPane.PALETTE_LAYER);
	addWindowListener(this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private function initComponents():void {
        var gridBagConstraints:java.awt.GridBagConstraints;

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        scrollingText = new javax.swing.JScrollPane();
        chat_Info_Area = new javax.swing.JEditorPane();
        member_List = new javax.swing.JList();
        chat_Text_Field = new javax.swing.JTextField();
        backgroundImage = new javax.swing.JLabel();
        main_Menu_Bar = new javax.swing.JMenuBar();
        Main_Menu = new javax.swing.JMenu();
        Menu_Options = new javax.swing.JMenuItem();
        selectBackgroundImage = new javax.swing.JMenuItem();
        selectDefaultTextColor = new javax.swing.JMenuItem();
        selectConnections = new javax.swing.JMenuItem();
        selectAdvertiseService = new javax.swing.JMenuItem();
        setBrowser = new javax.swing.JMenuItem();
        addChannel = new javax.swing.JMenuItem();
        followHyperlinks = new javax.swing.JCheckBoxMenuItem();
        solitaireMenu = new javax.swing.JMenu();
        watchSolitaire = new javax.swing.JMenuItem();
        dealSolitaire = new javax.swing.JMenuItem();
        randomPlayer = new javax.swing.JMenuItem();
        methodicalPlayer = new javax.swing.JMenuItem();
        flushContacts = new javax.swing.JMenuItem();
        flashchat = new javax.swing.JMenuItem();
        languageMenu = new javax.swing.JMenu();
        zh = new javax.swing.JMenuItem();
        zt = new javax.swing.JMenuItem();
        nl = new javax.swing.JMenuItem();
        en = new javax.swing.JMenuItem();
        fr = new javax.swing.JMenuItem();
        de = new javax.swing.JMenuItem();
        el = new javax.swing.JMenuItem();
        it = new javax.swing.JMenuItem();
        ja = new javax.swing.JMenuItem();
        ko = new javax.swing.JMenuItem();
        pt = new javax.swing.JMenuItem();
        ru = new javax.swing.JMenuItem();
        es = new javax.swing.JMenuItem();
        soundToggleItem = new javax.swing.JCheckBoxMenuItem();
        warmChicken = new javax.swing.JMenuItem();
        quit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LirCom");
        setName("Lircom"); // NOI18N

        jPanel1.setDoubleBuffered(false);
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 445));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 445));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        scrollingText.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollingText.setAlignmentY(1.0F);
        scrollingText.setAutoscrolls(true);
        scrollingText.setMinimumSize(new java.awt.Dimension(700, 420));
        scrollingText.setOpaque(false);
        scrollingText.setPreferredSize(new java.awt.Dimension(719, 420));

        chat_Info_Area.setContentType("text/html");
        chat_Info_Area.setToolTipText("chat history window");
        chat_Info_Area.setOpaque(false);
        chat_Info_Area.setPreferredSize(new java.awt.Dimension(700, 450));
        scrollingText.setViewportView(chat_Info_Area);

        jPanel1.add(scrollingText, new java.awt.GridBagConstraints());

        member_List.setBackground(new java.awt.Color(0, 0, 0));
        member_List.setForeground(new java.awt.Color(255, 255, 204));
        member_List.setToolTipText("Chatter List");
        member_List.setMinimumSize(new java.awt.Dimension(100, 420));
        member_List.setNextFocusableComponent(chat_Text_Field);
        member_List.setOpaque(false);
        member_List.setPreferredSize(new java.awt.Dimension(100, 420));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        jPanel1.add(member_List, gridBagConstraints);

        chat_Text_Field.setBackground(new java.awt.Color(0, 0, 0));
        chat_Text_Field.setForeground(new java.awt.Color(204, 255, 204));
        chat_Text_Field.setText("type here");
        chat_Text_Field.setCaretColor(new java.awt.Color(255, 255, 255));
        chat_Text_Field.setMinimumSize(new java.awt.Dimension(800, 25));
        chat_Text_Field.setNextFocusableComponent(member_List);
        chat_Text_Field.setPreferredSize(new java.awt.Dimension(800, 25));
        chat_Text_Field.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                chat_Text_FieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        jPanel1.add(chat_Text_Field, gridBagConstraints);

        jPanel1.setBounds(0, 0, 800, 445);
        jLayeredPane2.add(jPanel1, javax.swing.JLayeredPane.DRAG_LAYER);

        backgroundImage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lircom/Space_Tears_II.jpg"))); // NOI18N
        backgroundImage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        backgroundImage.setAlignmentY(1.0F);
        backgroundImage.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lircom/Space_Tears_II.jpg"))); // NOI18N
        backgroundImage.setOpaque(true);
        backgroundImage.setBounds(0, 0, 800, 455);
        jLayeredPane2.add(backgroundImage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane2, java.awt.BorderLayout.CENTER);

        Main_Menu.setText("Menu");
        Main_Menu.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                Main_MenuActionPerformed(evt);
            }
        });

        Menu_Options.setText("Options");
        Main_Menu.add(Menu_Options);

        selectBackgroundImage.setText("Select Background Image");
        selectBackgroundImage.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                popupFileDialog(evt);
            }
        });
        Main_Menu.add(selectBackgroundImage);

        selectDefaultTextColor.setText("Select Text Color");
        selectDefaultTextColor.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                selectDefaultTextColorActionPerformed(evt);
            }
        });
        Main_Menu.add(selectDefaultTextColor);

        selectConnections.setText("Connections");
        selectConnections.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                selectConnectionsActionPerformed(evt);
            }
        });
        Main_Menu.add(selectConnections);

        selectAdvertiseService.setText("Advertise Service");
        selectAdvertiseService.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                selectAdvertiseServiceActionPerformed(evt);
            }
        });
        Main_Menu.add(selectAdvertiseService);

        setBrowser.setText("Set Web Browser");
        setBrowser.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                setBrowserActionPerformed(evt);
            }
        });
        Main_Menu.add(setBrowser);

        addChannel.setText("Add Channel");
        addChannel.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                addChannelActionPerformed(evt);
            }
        });
        Main_Menu.add(addChannel);

        followHyperlinks.setText("Follow Hyperlinks");
        followHyperlinks.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                followHyperlinksActionPerformed(evt);
            }
        });
        Main_Menu.add(followHyperlinks);

        solitaireMenu.setText("Solitaire");
        solitaireMenu.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                solitaireMenuActionPerformed(evt);
            }
        });

        watchSolitaire.setText("Watch");
        watchSolitaire.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                watchSolitaireActionPerformed(evt);
            }
        });
        solitaireMenu.add(watchSolitaire);

        dealSolitaire.setText("Deal");
        dealSolitaire.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                dealSolitaireActionPerformed(evt);
            }
        });
        solitaireMenu.add(dealSolitaire);

        randomPlayer.setText("Computer Plays Randomly");
        randomPlayer.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                randomPlayerActionPerformed(evt);
            }
        });
        solitaireMenu.add(randomPlayer);

        methodicalPlayer.setText("Computer Plays Methodically");
        methodicalPlayer.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                methodicalPlayerActionPerformed(evt);
            }
        });
        solitaireMenu.add(methodicalPlayer);

        Main_Menu.add(solitaireMenu);

        flushContacts.setText("Flush Contacts");
        flushContacts.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                flushContactsActionPerformed(evt);
            }
        });
        Main_Menu.add(flushContacts);

        flashchat.setText("Flashchat");
        flashchat.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                flashchatActionPerformed(evt);
            }
        });
        Main_Menu.add(flashchat);

        languageMenu.setText("Language");

        zh.setText("??");
        zh.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                zhActionPerformed(evt);
            }
        });
        languageMenu.add(zh);

        zt.setText("??");
        zt.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                ztActionPerformed(evt);
            }
        });
        languageMenu.add(zt);

        nl.setText("Nederlands");
        nl.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                nlActionPerformed(evt);
            }
        });
        languageMenu.add(nl);

        en.setText("English");
        en.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                enActionPerformed(evt);
            }
        });
        languageMenu.add(en);

        fr.setText("Franais");
        fr.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                frActionPerformed(evt);
            }
        });
        languageMenu.add(fr);

        de.setText("Deutsch");
        de.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                deActionPerformed(evt);
            }
        });
        languageMenu.add(de);

        el.setText("????????");
        el.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                elActionPerformed(evt);
            }
        });
        languageMenu.add(el);

        it.setText("italiano");
        it.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                itActionPerformed(evt);
            }
        });
        languageMenu.add(it);

        ja.setText("???");
        ja.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                jaActionPerformed(evt);
            }
        });
        languageMenu.add(ja);

        ko.setText("???");
        ko.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                koActionPerformed(evt);
            }
        });
        languageMenu.add(ko);

        pt.setText("Portugus");
        pt.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                ptActionPerformed(evt);
            }
        });
        languageMenu.add(pt);

        ru.setText("??????");
        ru.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                ruActionPerformed(evt);
            }
        });
        languageMenu.add(ru);

        es.setText("espaol");
        es.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                esActionPerformed(evt);
            }
        });
        languageMenu.add(es);

        Main_Menu.add(languageMenu);

        soundToggleItem.setText("Toggle Sound");
        soundToggleItem.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                soundToggleItemActionPerformed(evt);
            }
        });
        Main_Menu.add(soundToggleItem);

        warmChicken.setLabel("Warm Chicken");
        warmChicken.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                warmChickenActionPerformed(evt);
            }
        });
        Main_Menu.add(warmChicken);

        quit.setText("Quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                quitActionPerformed(evt);
            }
        });
        Main_Menu.add(quit);

        main_Menu_Bar.add(Main_Menu);

        setJMenuBar(main_Menu_Bar);

        var screenSize:java.awt.Dimension= java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-500)/2, 800, 500);
    }// </editor-fold>//GEN-END:initComponents

    private function warmChickenActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_warmChickenActionPerformed
            try {
		heathens = new Heathens(chat, nickname);
	    } catch (var e:Exception) {
	    }
    }//GEN-LAST:event_warmChickenActionPerformed

    private function soundToggleItemActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_soundToggleItemActionPerformed
        chat.toggleSound();
    }//GEN-LAST:event_soundToggleItemActionPerformed

    private function ztActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_ztActionPerformed
        chat.setLanguage("zt");
    }//GEN-LAST:event_ztActionPerformed

    private function zhActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_zhActionPerformed
        chat.setLanguage("zh");
    }//GEN-LAST:event_zhActionPerformed

    private function esActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_esActionPerformed
        chat.setLanguage("es");
    }//GEN-LAST:event_esActionPerformed

    private function ruActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_ruActionPerformed
        chat.setLanguage("ru");
    }//GEN-LAST:event_ruActionPerformed

    private function ptActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_ptActionPerformed
        chat.setLanguage("pt");
    }//GEN-LAST:event_ptActionPerformed

    private function koActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_koActionPerformed
        chat.setLanguage("ko");
    }//GEN-LAST:event_koActionPerformed

    private function jaActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_jaActionPerformed
        chat.setLanguage("ja");
    }//GEN-LAST:event_jaActionPerformed

    private function itActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_itActionPerformed
        chat.setLanguage("it");
    }//GEN-LAST:event_itActionPerformed

    private function elActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_elActionPerformed
        chat.setLanguage("el");
    }//GEN-LAST:event_elActionPerformed

    private function frActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_frActionPerformed
       chat.setLanguage("fr");
    }//GEN-LAST:event_frActionPerformed

    private function nlActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_nlActionPerformed
       chat.setLanguage("nl");
    }//GEN-LAST:event_nlActionPerformed

    private function deActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_deActionPerformed
        chat.setLanguage("de");
    }//GEN-LAST:event_deActionPerformed

    private function enActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_enActionPerformed
        chat.setLanguage("en");
    }//GEN-LAST:event_enActionPerformed

    private function flashchatActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_flashchatActionPerformed
	    try {
		var r:Runestone= new Runestone(chat, nickname);
	    } catch (var e:Exception) {
	    }
    }//GEN-LAST:event_flashchatActionPerformed

    private function flushContactsActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_flushContactsActionPerformed
        chat.flushContacts();
    }//GEN-LAST:event_flushContactsActionPerformed

    private function randomPlayerActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_randomPlayerActionPerformed
        try {
            startSolitaire("random");
        } catch (var e:Exception) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_randomPlayerActionPerformed

    private function dealSolitaireActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_dealSolitaireActionPerformed
        try {
            startSolitaire("dealer");
        } catch (var e:Exception) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_dealSolitaireActionPerformed

    private function methodicalPlayerActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_methodicalPlayerActionPerformed
        try {
            startSolitaire("methodical");
        } catch (var e:Exception) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_methodicalPlayerActionPerformed

    private function solitaireMenuActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_solitaireMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_solitaireMenuActionPerformed

    private function Main_MenuActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_Main_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Main_MenuActionPerformed

    private function watchSolitaireActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_watchSolitaireActionPerformed
        try {
            startSolitaire("display");
        } catch (var e:Exception) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_watchSolitaireActionPerformed

    private function followHyperlinksActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_followHyperlinksActionPerformed
        chat_Info_Area.setEditable(!chat_Info_Area.isEditable());
    }//GEN-LAST:event_followHyperlinksActionPerformed

    private function addChannelActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_addChannelActionPerformed
        try {
 
		var classname:String= javax.swing.JOptionPane.showInputDialog(this, "Enter classname:", "lircom.Channel");
		var newChannel:MainWindow= new MainWindow(classname);
		newChannel.nickname = javax.swing.JOptionPane.showInputDialog(this, "Enter nickname:", "Guest");
		newChannel.setTitle(newChannel.nickname);
		newChannel.setChat(classname, newChannel.nickname);
		newChannel.setVisible(true);
		newChannel.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		// newChannel.bridge = new IRCBridge(newChannel.chat, newChannel.nickname);
        } catch (var e:Exception) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_addChannelActionPerformed

    private function setBrowserActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_setBrowserActionPerformed
        var chooser:javax.swing.JFileChooser= new javax.swing.JFileChooser();
        if (currentBrowserDirectory != null) {
          chooser.setCurrentDirectory(currentBrowserDirectory);
        }
        var returnVal:int= chooser.showOpenDialog(this);
        if(returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            browser = chooser.getSelectedFile().getAbsolutePath();
            hyperlinkHandler.setBrowser(browser);
            currentBrowserDirectory = chooser.getCurrentDirectory();
        }
    }//GEN-LAST:event_setBrowserActionPerformed

    private function selectAdvertiseServiceActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_selectAdvertiseServiceActionPerformed
        if (serverAdvertise == null) {
                serverAdvertise = new ServerAdvertise();
        }
        serverAdvertise.setChat(chat);
        serverAdvertise.setVisible(true);
        serverAdvertise.setTitle("serverAdvertise");
    }//GEN-LAST:event_selectAdvertiseServiceActionPerformed

    private function selectConnectionsActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_selectConnectionsActionPerformed
        if (clientConnect == null) {
            clientConnect = new ClientConnect(this);
        }
        clientConnect.setVisible(true);
        clientConnect.harvest();
    }//GEN-LAST:event_selectConnectionsActionPerformed

    private function selectDefaultTextColorActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_selectDefaultTextColorActionPerformed
        // TODO add your handling code here:
        if (currentTextColor == null) {
               currentTextColor =  java.awt.Color.getColor("#FFFFFF");
        }
        if (currentTextColor == null) {
            currentTextColor = java.awt.Color.WHITE;
        }
        var chooser:javax.swing.JColorChooser= new javax.swing.JColorChooser(currentTextColor);
        currentTextColor = chooser.showDialog(this, "Select default text color", currentTextColor);
        var red:String= Integer.toHexString(currentTextColor.getRed());
        if (red.length() == 1) {
                red = "0"+red;
        }
        var green:String= Integer.toHexString(currentTextColor.getGreen());
        if (green.length() == 1) {
                green = "0"+green;
        }
        var blue:String= Integer.toHexString(currentTextColor.getBlue());
        if (blue.length() == 1) {
                blue = "0"+blue;
        }
        var color:String= "#"+red+green+blue;
        chat.setColor(color);
    }//GEN-LAST:event_selectDefaultTextColorActionPerformed

    private function chat_Text_FieldActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_chat_Text_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chat_Text_FieldActionPerformed

    private function popupFileDialog(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_popupFileDialog
    var chooser:javax.swing.JFileChooser= new javax.swing.JFileChooser();
    if (currentDirectory != null) {
        chooser.setCurrentDirectory(currentDirectory);
    }
    // Note: source for ExampleFileFilter can be found in FileChooserDemo,
    // under the demo/jfc directory in the Java 2 SDK, Standard Edition.
    var filter:ExampleFileFilter= new ExampleFileFilter();
    filter.addExtension("jpg");
    filter.addExtension("gif");
    filter.setDescription("JPG & GIF Images");
    chooser.setFileFilter(filter);
    var returnVal:int= chooser.showOpenDialog(this);
    if(returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
        backgroundImage.setIcon(new javax.swing.ImageIcon(chooser.getSelectedFile().getAbsolutePath()));
        currentDirectory = chooser.getCurrentDirectory();
    }
    }//GEN-LAST:event_popupFileDialog

    private function quitActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_quitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed
    
    /**
     * @param args the command line arguments
     */
    static var args:Array;
    public static function main(String chatargs[]):void {
	try {
	  //UIManager.setLookAndFeel(
	    //UIManager.getCrossPlatformLookAndFeelClassName());
	} catch (var e:Exception) {
	}
	args = chatargs;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public function run():void {
		try {
			var lircomwindow:MainWindow= new MainWindow("LirCom");
			var classname:String= "lircom.Chat";
			if (args.length > 0) {
				classname = args[0];
			} else {
				classname = javax.swing.JOptionPane.showInputDialog("Enter classname:", "lircom.Chat");
			}
			if (classname == null) {
				classname = "lircom.Chat";
			}
			lircomwindow.nickname = "Guest";
			if (args.length > 1) {
				lircomwindow.nickname = args[1];
			} else {
				lircomwindow.nickname = javax.swing.JOptionPane.showInputDialog("Enter nickname:");
			}
			if (lircomwindow.nickname == null) {
				System.exit(0);
			}
			lircomwindow.setTitle(lircomwindow.nickname);
			lircomwindow.setChat(classname, lircomwindow.nickname);
			var url:String= "irc://irc.ircstorm.net:6667/schizophrenia";
			if (args.length > 2) {
				url = args[2];
			} else {
				url = javax.swing.JOptionPane.showInputDialog("Enter url:", url);
			}
			if (url == null) {
				System.exit(0);
			}

                        // lircomwindow.setVisible(true);
                        // lircomwindow.selectConnectionsActionPerformed(null);
			lircomwindow.bridge = new IRCBridge(lircomwindow.chat, lircomwindow.nickname, url, lircomwindow);
    			// lircomwindow.warmChickenActionPerformed(null);
                        // lircomwindow.flashchatActionPerformed(null);
 
                } catch (var e:Exception) {
			System.err.println("Died");
			e.printStackTrace();
		}
                
            }
        });
    }
    public function setChat(classname:String, nickname:String):void throws Exception {
		try {
			chat = Chat((Class.forName(classname).newInstance()));
		} catch (var e:Exception) {
			chat = new Chat();
		}
		chat.setNick(nickname);
		init(chat);
    }
    public function connect(server:String, port:int):void throws Exception {
		var client:ClientOnServer= new ClientOnServer(server, port);
		client.start();
    }
    public function init(chat:Chat):void throws Exception {
		var fg:FromGUI= new FromGUI();
		var fs:FromServer= new FromServer();
		chat.setInputStream(fg);
		chat.setOutputStream(fs);
		fs.setChat(chat);
                //chat.connect(remoteServer, remotePort); 
                System.err.println("Channel id is "+chat.clientno);
                
                chat.jp = member_List;
                chat.tf = chat_Text_Field;
                chat.ta = chat_Info_Area;
                chat.init();
                chat.start();
                hyperlinkHandler = new Hyperactive();
                chat_Info_Area.addHyperlinkListener(hyperlinkHandler);
    }
    public function startSolitaire(mode:String):void throws Exception {
            var g:solitaire.Game= new solitaire.Game();
//            try {
//                g.startGame(mode, heathens, nickname);
//                return;
//            } catch (Exception ex) {
//                ex.printStackTrace();
//            }
            var i:java.util.Iterator= PossibleConnection.iterator();

            while (i.hasNext()) {
                var pcon:PossibleConnection= PossibleConnection(PossibleConnection.get(i.next()));
                if (pcon.connected) {
                    try {
                        g.startGame(mode, pcon.host, Integer.parseInt(pcon.port), nickname);
                        return;
                    } catch (var ex:Exception) {
                        ex.printStackTrace();
                        pcon.connected = false;
                    }
                }
 
            }
            selectConnectionsActionPerformed(null);      
    }
public function windowActivated(e:java.awt.event.WindowEvent):void {}
public function windowClosed(e:java.awt.event.WindowEvent):void {}
public function windowClosing(e:java.awt.event.WindowEvent):void { System.exit(0); }
public function windowDeactivated(e:java.awt.event.WindowEvent):void {}
public function windowDeiconified(e:java.awt.event.WindowEvent):void {}
public function windowIconified(e:java.awt.event.WindowEvent):void {}
public function windowOpened(e:java.awt.event.WindowEvent):void {}
    private var nickname:String;
    private var hyperlinkHandler:Hyperactive;
    private var browser:String;
    private var currentBrowserDirectory:java.io.File;
    private var serverAdvertise:ServerAdvertise;
    private var clientConnect:ClientConnect;
    private var bridge:IRCBridge;
    public var chat:Chat;
    private var heathens:Heathens;
    private var currentTextColor:java.awt.Color;
    private var currentDirectory:java.io.File;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private var Main_Menu:javax.swing.JMenu;
    private var Menu_Options:javax.swing.JMenuItem;
    private var addChannel:javax.swing.JMenuItem;
    private var backgroundImage:javax.swing.JLabel;
    private var chat_Info_Area:javax.swing.JEditorPane;
    private var chat_Text_Field:javax.swing.JTextField;
    private var de:javax.swing.JMenuItem;
    private var dealSolitaire:javax.swing.JMenuItem;
    private var el:javax.swing.JMenuItem;
    private var en:javax.swing.JMenuItem;
    private var es:javax.swing.JMenuItem;
    private var flashchat:javax.swing.JMenuItem;
    private var flushContacts:javax.swing.JMenuItem;
    private var followHyperlinks:javax.swing.JCheckBoxMenuItem;
    private var fr:javax.swing.JMenuItem;
    private var it:javax.swing.JMenuItem;
    private var jLayeredPane2:javax.swing.JLayeredPane;
    private var jPanel1:javax.swing.JPanel;
    private var ja:javax.swing.JMenuItem;
    private var ko:javax.swing.JMenuItem;
    private var languageMenu:javax.swing.JMenu;
    private var main_Menu_Bar:javax.swing.JMenuBar;
    private var member_List:javax.swing.JList;
    private var methodicalPlayer:javax.swing.JMenuItem;
    private var nl:javax.swing.JMenuItem;
    private var pt:javax.swing.JMenuItem;
    private var quit:javax.swing.JMenuItem;
    private var randomPlayer:javax.swing.JMenuItem;
    private var ru:javax.swing.JMenuItem;
    private var scrollingText:javax.swing.JScrollPane;
    private var selectAdvertiseService:javax.swing.JMenuItem;
    private var selectBackgroundImage:javax.swing.JMenuItem;
    private var selectConnections:javax.swing.JMenuItem;
    private var selectDefaultTextColor:javax.swing.JMenuItem;
    private var setBrowser:javax.swing.JMenuItem;
    private var solitaireMenu:javax.swing.JMenu;
    private var soundToggleItem:javax.swing.JCheckBoxMenuItem;
    private var warmChicken:javax.swing.JMenuItem;
    private var watchSolitaire:javax.swing.JMenuItem;
    private var zh:javax.swing.JMenuItem;
    private var zt:javax.swing.JMenuItem;
    // End of variables declaration//GEN-END:variables
    
}
}