/*
 * ServerAdvertise.java
 *
 * Created on February 13, 2005, 4:02 PM
 */

package lircom {
/**
 *
 * @author  carlsonj
 */
public class ServerAdvertise extends javax.swing.JFrame {
    
    /** Creates new form ServerAdvertise */
    public function ServerAdvertise() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private function initComponents():void {
        var gridBagConstraints:java.awt.GridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        advertisementPort = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        url = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nickname = new javax.swing.JTextField();
        advertiseButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Service Advertisement Port");
        getContentPane().add(jLabel3, new java.awt.GridBagConstraints());

        advertisementPort.setColumns(40);
        advertisementPort.setText("8180");
        advertisementPort.setMinimumSize(new java.awt.Dimension(200, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        getContentPane().add(advertisementPort, gridBagConstraints);

        jLabel1.setText("Advertisement Service URL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        getContentPane().add(jLabel1, gridBagConstraints);

        url.setColumns(40);
        url.setText("http://coderextreme.net/advertise.php");
        url.setMinimumSize(new java.awt.Dimension(200, 19));
        url.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                urlActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        getContentPane().add(url, gridBagConstraints);

        jLabel5.setText("Your Server Name");
        getContentPane().add(jLabel5, new java.awt.GridBagConstraints());

        nickname.setColumns(40);
        nickname.setMinimumSize(new java.awt.Dimension(200, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        getContentPane().add(nickname, gridBagConstraints);

        advertiseButton.setText("Advertise");
        advertiseButton.addActionListener(new java.awt.event.ActionListener() {
            public function actionPerformed(evt:java.awt.event.ActionEvent):void {
                advertiseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(advertiseButton, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private function advertiseButtonActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_advertiseButtonActionPerformed
                java.awt.EventQueue.invokeLater(new Runnable() {
                public function run():void {
                    try {
                       var p:Peer= new Peer();
                       var adurl:String= "";
			p.setPort(Integer.parseInt(advertisementPort.getText()));
			if (!p.isAlive()) {
			    p.start();
			}
                       adurl = url.getText()+"?port="+advertisementPort.getText()+"&nick="+nickname.getText();
                       System.err.println("url is "+adurl);
                       var u:java.net.URL= new java.net.URL(adurl);
                       var conn:java.net.URLConnection= u.openConnection();
                       conn.setDoInput(true);
                       conn.setDoOutput(true);
                       conn.connect();
                       // conn.getOutputStream().close();
                       var br:java.io.BufferedReader= new java.io.BufferedReader(new java.io.InputStreamReader(conn.getInputStream()));
                       var line:String;
                       while ((line = br.readLine()) != null) {
                                System.err.println(line);
                       }
                       setVisible(false);
                    } catch (var e:Exception) {
                       System.err.println("Networking problems "+e.getMessage());
                       e.printStackTrace();
                    }
               }
            });

    }//GEN-LAST:event_advertiseButtonActionPerformed

    private function urlActionPerformed(evt:java.awt.event.ActionEvent):void {//GEN-FIRST:event_urlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static function main(String args[]):void {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public function run():void {
                new ServerAdvertise().setVisible(true);
            }
        });
    }
    public function setChat(chat:Chat):void {
       this.chat = chat;
    }
    var chat:Chat;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private var advertiseButton:javax.swing.JButton;
    private var advertisementPort:javax.swing.JTextField;
    private var jLabel1:javax.swing.JLabel;
    private var jLabel3:javax.swing.JLabel;
    private var jLabel5:javax.swing.JLabel;
    private var nickname:javax.swing.JTextField;
    private var url:javax.swing.JTextField;
    // End of variables declaration//GEN-END:variables
    
}
}